function [ll] = GMM_loglikelihood(X, theta)
% Calculate the log likelihood of X, given a mixture model.
% 
% The model assumes each column of x is independently generated by a
% mixture model with parameters theta.
%
% Arguments
%  X - A DxM matrix, whose every column corresponds to a patch in D
%      dimensions (typically D=64).
%  theta - A struct with fields:
%          means - A KxD matrix where K is the number of components in
%                  mixture and D is the dimension of the data.
%          covs - A DxDxK array whose every page is a covariance matrix of
%                 the corresponding component.
%          mix - A Kx1 vector with mixing proportions.
%

% =========================================================================
% This is an optional file
% =========================================================================

[D, M] = size(X);
[K, L] = size(theta.mix);
ll = 0;
for i=1:M
    sum_xi = 0;
    for j=1:K
        sum_xi = sum_xi + mvnpdf(transpose(X(:,i)), theta.means(j,:), theta.covs(:,:,j)) * theta.mix(j);
    end

    sum_xi = log(sum_xi);
    ll = ll + sum_xi;
end
end