function [xhat] = ICA_denoise(y, ica, noise)
% Denoises every column in y, assuming an ICA model and white noise.
% 
% The model assumes that y = x + noise where x is generated by a ICA
% 0-mean mixture model.
%
% Arguments
%  y - A DxM matrix, whose every column corresponds to a patch in D
%      dimensions (typically D=64).
%  ica - A struct with fields:
%           P - mixing matrix of sources (P: D ind. sources -> D signals)
%           vars - a DxK matrix whose (d,k) element correponsds to the
%                  variance of the k'th component in dimension d.
%           mix - a DxK matrix whose (d,k) element correponsds to the
%                 mixing weight of the k'th component in dimension d.
%  noise - the std of the noise in y.
%
[D, M] = size(y);
PTy = transpose(ica.P) * y; % s + noise2
shat = zeros(D, M);
%for sample=1:M
for cord=1:D
    gmm = struct();
    gmm.covs = ica.covs(cord,:,:,:);
    gmm.mix = ica.mix(cord,:);
    gmm.means = ica.means(cord,:,:);
    % notice: no means sent
    shat(cord, :) = GMM_denoise(y(cord,:), gmm, noise);
end
% mult by PT
xhat = ica.P * y;
end