function [ll] = ICA_loglikelihood(X, model)
% Calculate the log likelihood of X, given an ICA model.
% 
% The model assumes each column of x is independently generated by a
% mixture model with parameters theta.
%
% Arguments
%  X - A DxM matrix, whose every column corresponds to a patch in D
%      dimensions (typically D=64).
%  model - A struct with fields:
%           P - mixing matrix of sources (P: D ind. sources -> D signals)
%           vars - a DxK matrix whose (d,k) element correponsds to the
%                  variance of the k'th component in dimension d.
%           mix - a DxK matrix whose (d,k) element correponsds to the
%                 mixing weight of the k'th component in dimension d.
%
ll = 0;
[D, K] = size(model.mix);
S = model.P' * X;

for si=1:D % every si
    tetha = struct();
    tetha.means = model.means(si,:,:);
    tetha.covs = model.covs(si,:,:,:);
    tetha.mix = model.mix(si,:);
    ll = ll + GMM_loglikelihood(S(si,:), tetha);
end
end