function [xhat] = MVN_denoise(y, mvn, noise)
% Denoises every column in y, assuming an MVN model and white noise.
% 
% The model assumes that y = x + noise where x is generated by a single
% 0-mean multi-variate normal distribution.
%
% Arguments
%  y - A DxM matrix, whose every column corresponds to a patch in D
%      dimensions (typically D=64).
%  mvn - A struct with field:
%           cov - A DxD covariane matrix.
%  noise - the std of the noise in y.
%
[D, M] = size(y);
xhat = nan(D, M);
for one_sample=1:M
    xhat(:,one_sample) = inv(inv(mvn.cov) + (1/(noise*noise))*(eye(D,D))) * (1/(noise*noise)* y(:,one_sample));
end
end